---
title: "Results_visualization"
author: "Michael Balmer"
date: "25 1 2020"
output: rmarkdown::github_document
---

```{r, warning=FALSE, message=FALSE, fig.align="center"}
mae_1h_ahead_fs1 <- c()
mae_1h_ahead_fs2 <- c()
mae_1h_ahead_fs3 <- c()
mae_1h_ahead_fs4 <- c()
mae_1h_ahead_fs5 <- c()
mae_1h_ahead_fs6 <- c()
mae_1h_ahead_fs7 <- c()
mae_1h_ahead_fs8 <- c()

mae_1h_ahead_fs1nn <- c()
mae_1h_ahead_fs2nn <- c()
mae_1h_ahead_fs3nn <- c()
mae_1h_ahead_fs4nn <- c()
mae_1h_ahead_fs8nn <- c()


for (i in 1:10){
  mae1fs1 <- run_featureset_two[[i]]$mean_mae[9]
  mae1fs2 <- run_featureset_four[[i]]$mean_mae[9]
  mae1fs3 <- run_featureset_six[[i]]$mean_mae[9]
  mae1fs4 <- run_featureset_eight[[i]]$mean_mae[9]
  mae1fs5 <- run_featureset_eleven[[i]]$mean_mae[9]
  mae1fs6 <- run_featureset_twelve[[i]]$mean_mae[9]
  mae1fs7 <- run_featureset_thirteen[[i]]$mean_mae[9]
  mae1fs8 <- run_featureset_ten[[i]]$mean_mae[9]
  ##nn
  mae1fs1nn <- run_featureset_two_nn[[i]]$mean_mae[9]
  mae1fs2nn <- run_featureset_four_nn[[i]]$mean_mae[9]
  mae1fs3nn <- run_featureset_six_nn[[i]]$mean_mae[9]
  mae1fs4nn <- run_featureset_eight_nn[[i]]$mean_mae[9]
  mae1fs8nn <- run_featureset_ten_nn[[i]]$mean_mae[9]
  
  mae_1h_ahead_fs1 <- c(mae_1h_ahead_fs1,mae1fs1)
  mae_1h_ahead_fs2 <- c(mae_1h_ahead_fs2,mae1fs2)
  mae_1h_ahead_fs3 <- c(mae_1h_ahead_fs3,mae1fs3)
  mae_1h_ahead_fs4 <- c(mae_1h_ahead_fs4,mae1fs4)
  mae_1h_ahead_fs5 <- c(mae_1h_ahead_fs5,mae1fs5)
  mae_1h_ahead_fs6 <- c(mae_1h_ahead_fs6,mae1fs6)
  mae_1h_ahead_fs7 <- c(mae_1h_ahead_fs7,mae1fs7)
  mae_1h_ahead_fs8 <- c(mae_1h_ahead_fs8,mae1fs8)
  ##nn
  mae_1h_ahead_fs1nn <- c(mae_1h_ahead_fs1nn,mae1fs1nn)
  mae_1h_ahead_fs2nn <- c(mae_1h_ahead_fs2nn,mae1fs2nn)
  mae_1h_ahead_fs3nn <- c(mae_1h_ahead_fs3nn,mae1fs3nn)
  mae_1h_ahead_fs4nn <- c(mae_1h_ahead_fs4nn,mae1fs4nn)
  mae_1h_ahead_fs8nn <- c(mae_1h_ahead_fs8nn,mae1fs8nn)
  
}

rf_plot_traindays_9h <- cbind.data.frame(c(1:10),mae_1h_ahead_fs1,mae_1h_ahead_fs2,
                                      mae_1h_ahead_fs3,mae_1h_ahead_fs4,
                                      mae_1h_ahead_fs5,mae_1h_ahead_fs6,mae_1h_ahead_fs7,
                                      mae_1h_ahead_fs8)
names(rf_plot_traindays_9h) <- c('train_days','1','2','3','4','5','6','7','8')

rf_plot_traindays_9h <- melt(rf_plot_traindays_9h, id='train_days')


nn_plot_traindays_9h <- cbind.data.frame(c(1:10),mae_1h_ahead_fs1nn,
                                      mae_1h_ahead_fs2nn,mae_1h_ahead_fs3nn,
                                      mae_1h_ahead_fs4nn,mae_1h_ahead_fs8nn)

names(nn_plot_traindays_9h) <- c('train_days','1',
                              '2','3',
                              '4','8')

nn_plot_traindays_9h <- melt(nn_plot_traindays_9h, id='train_days')
```

this

```{r, warning=FALSE, message=FALSE, fig.align="center"}
###1h ahead prediction

####RF
##MAE of different feature sets as a function of traing days (1h ahead pred)
rf_plot_ktraindays_1h <- ggplot(rf_plot_traindays_1h[-c(41:70),], 
                                aes(train_days,value))+
  geom_line(aes(colour=variable),size=.7)+
  theme_bw()+
  scale_colour_manual(values=c('#808080','#0000FF','#ff0000','#008000','#252525'))+
  labs(x = "Training dataset size (days)", y = "MAE") +
  scale_x_continuous(breaks = seq(1, 10, 1),expand = c(0,0)) +
  scale_y_continuous(limits=c(0.065,0.075),breaks=seq(0.065,0.075,0.0025),expand = c(0,0))+
  theme(plot.title = element_text(size = 12, face = "bold"),
        legend.title=element_text(size=9),
        legend.text=element_text(size=8),
        legend.key.size = unit(.4,"cm"),
        legend.box.background = element_rect(colour = "black"),
        legend.position = c(0.88,0.12),legend.direction = 'vertical',
        panel.grid.minor.x = element_blank(),
        plot.margin = unit(c(0.5,0.5,2,0.5), "cm"))+
  guides(colour = guide_legend(title.position = "top"))+
  annotation_custom(text_annotation_a,xmin=0,xmax=0,ymin=0,ymax=0)+
  labs(colour = "Feature set")

rf_plot_ktraindays_1h


####NN
##MAE of different feature sets as a function of traing days (1h ahead pred)
nn_plot_ktraindays_1h <- ggplot(nn_plot_traindays_1h, aes(train_days,value))+
  geom_line(aes(colour=variable),size=.7)+
  theme_bw()+
  scale_colour_manual(values=c('#808080','#0000FF','#ff0000','#008000','#252525'))+
  labs(x = "Training dataset size (days)", y = "MAE") +
  scale_x_continuous(breaks = seq(1, 10, 1),expand = c(0,0)) +
  scale_y_continuous(limits=c(0.075,0.155),breaks=seq(0.075,0.155,0.02),expand = c(0,0))+
  theme(plot.title = element_text(size = 12, face = "bold"),
        legend.title=element_text(size=9),
        legend.text=element_text(size=8),
        legend.key.size = unit(.4,"cm"),
        legend.box.background = element_rect(colour = "black"),
        legend.position = c(0.88,0.88),legend.direction = 'vertical',
        panel.grid.minor.x = element_blank(),
        plot.margin = unit(c(0.5,0.5,2,0.5), "cm"))+
  guides(colour = guide_legend(title.position = "top"))+
  labs(colour = "Feature set")

nn_plot_ktraindays_1h

##combine both plots
plot_grid(
  rf_plot_ktraindays_1h, nn_plot_ktraindays_1h,align = "hv", ncol = 2,
  labels = c('(a) RF', '(b) ANN'),label_size = 12,label_x = 0.5, label_y = 0,
  hjust = 0.5, vjust = -2.5,label_fontface = 'plain'
)
```
